[epa-paris-saclay.fr]
title = "Paris Saclay"
url = "https://epa-paris-saclay.fr/actualites-et-decryptages/format/actualites/"
entrySelector = ".section.main-search-results"
titleSelector = "h3"
linkSelector = "h3 a"

[lve-project.org]
url = "https://lve-project.org/blog/"
entrySelector = ".content.blog"
titleSelector = "h1"
linkSelector = "h1 a"
