[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[wikivoyage]
title = "Paris Saclay"
url = "https://epa-paris-saclay.fr/actualites-et-decryptages/format/actualites/"
entrySelector = ".section.main-search-results"
titleSelector = "h3"
linkSelector = "h3 a"
